# Github Pages Configuration for FIDO POC
title: 'POC FIDO Standalone - Mercado Pago'
description: 'POC de integração FIDO Standalone com WebAuthn real para teste em dispositivos móveis'
url: 'https://icaldana.github.io'
baseurl: '/github-poc'

# Security headers
plugins:
  - jekyll-redirect-from

# Force HTTPS
enforce_ssl: icaldana.github.io

# Allow iframe embedding (needed for FIDO iframe)
webrick:
  headers:
    Access-Control-Allow-Origin: '*'
    Access-Control-Allow-Methods: 'GET,POST,OPTIONS'
    Access-Control-Allow-Headers: 'Content-Type'
    Content-Security-Policy: "frame-ancestors 'self' https://icaldana.github.io; frame-src 'self' https://icaldana.github.io"
